
export enum OrderStatus {
  RECEIVED = 'RECEIVED',
  FINALIZATION = 'FINALIZATION',
  IN_PRODUCTION = 'IN_PRODUCTION',
  SUBLIMATION = 'SUBLIMATION',
  FINISHED = 'FINISHED',
  // Loja Virtual Flow
  STORE_REQUEST = 'STORE_REQUEST',       // Solicitação recebida
  STORE_CONFERENCE = 'STORE_CONFERENCE', // Em conferência
  STORE_CHECKED = 'STORE_CHECKED',       // Pedido conferido (Ready for Sales Approval)
  CANCELLED = 'CANCELLED'
}

export enum OrderType {
  SALE = 'SALE',
  BUDGET = 'BUDGET'
}

export type FabricType = 'premium' | 'técnico' | 'econômico';

export interface Fabric {
  id: string;
  name: string;
  type: FabricType;
  costPerMeter: number;
  compatibility: string;
  leadTimeImpact: number;
}

export interface SizeGrade {
  label: string;
  sizes: string[];
}

export interface OrderItem {
  id: string;
  productId: string;
  productName: string;
  fabricId: string;
  fabricName: string;
  gradeLabel: string;
  size: string;
  quantity: number;
  unitPrice: number;
  supplierId?: string;  // Fornecedor específico deste item
  unitCost?: number;    // Custo snapshot (do product_suppliers) no momento do pedido
  selectedVariations?: Record<string, string>; // { categoryName: optionLabel }
  selectedAddons?: ProductAddon[]; // New: Adicionais selecionados (ex: Nome +R$ 10)
  notes?: string;
}



export enum PaymentStatus {
  FULL = 'Integral (100%)',
  HALF = 'Sinal (50%)',
  DEPOSIT = 'Sinal / Parcial', // Custom amount
  PENDING = 'Pendente'
}

export interface Order {
  id: string;
  orderNumber: string;
  clientId: string;
  clientName: string;
  status: OrderStatus;
  paymentStatus?: PaymentStatus;
  origin?: 'manual' | 'store' | 'support'; // Origin of the order
  assignedSeller?: string; // Salesperson handling the chat
  orderType: OrderType;
  items: OrderItem[];
  totalValue: number;
  totalCost?: number; // Total cost based on supplier prices
  discountValue?: number; // New: Value of discount applied
  amountPaid?: number; // New: Custom partial payment amount
  supplierId?: string; // Selected supplier for margin calculation
  createdAt: string;
  deliveryDate: string;
  notes?: string;
  internalNotes?: string;
  delayReason?: string;
  layoutUrl?: string; // Legacy: single image url (kept for compatibility)
  layoutUrls?: string[]; // New: Multiple image urls for approved layouts
  designFileUrls?: string[]; // New: Source files (PSD, CDR, RAR)
  readyFileUrls?: string[]; // New: Print-ready files
  artCreated?: boolean; // Art Queue: art has been created
  artAwaitingApproval?: boolean; // Art Queue: art is awaiting client approval
  layoutRevision?: string; // Art Queue: revision/layout number
  fiscalKey?: string; // Simulated NFe Access Key
  clientTeam?: string; // Turma/Time (from Store)
  productionStep?: string; // IMPRESSAO, PRENSA, COSTURA, CONFERENCIA
  briefing?: string; // AI briefing generated by CloudBot
}

export interface ProductSupplier {
  id?: string;
  product_id?: string;
  supplier_id: string;
  supplier?: Supplier; // Virtual field for UI
  cost_price: number;
  is_default: boolean;
}

/**
 * Uma opção dentro de uma categoria de material (ex: 'Dry Fit Premium' dentro de 'Tecido')
 */
export interface MaterialOption {
  id: string;   // uuid local
  label: string; // Nome da opção
  costDelta?: number; // Custo adicional desta opção (opcional)
}

/**
 * Uma categoria de material customizável por produto
 * Exemplos: 'Tecido', 'Cor do Fio', 'Espessura', 'Acabamento'
 */
export interface MaterialVariation {
  id: string;       // uuid local
  name: string;     // Nome da categoria
  required: boolean; // Se é obrigatório selecionar no pedido
  options: MaterialOption[];
}

export interface ProductAddon {
  id: string;
  name: string;
  price: number;
}

export interface Product {
  id: string;
  sku: string;
  name: string;
  category?: string; // Legado (pode ser usado como fallback)
  categories?: string[]; // Novo: múltiplas escolhas de categoria
  status: 'active' | 'inactive';
  imageUrl: string;
  backImageUrl?: string; // New: Back side image
  basePrice: number;
  costPrice?: number; // Cost Price for Profit Calculation
  stock?: number; // Available inventory for this specific product
  description?: string; // Commercial description
  allowedGrades?: Record<string, string[]>;
  measurements?: Record<string, { height: string; width: string }>; // Size measurements
  published?: boolean; // Controls visibility in Public Store
  suppliers?: ProductSupplier[]; // Associated suppliers
  materialVariations?: MaterialVariation[]; // Variações de material customizáveis por produto
  addons?: ProductAddon[]; // Adicionais cobrados à parte (ex: Nome, Número)
}

export interface Supplier {
  id: string;
  name: string;
  contact_name?: string;
  whatsapp?: string;
  notes?: string;
  created_at?: string;
}

export interface Client {
  id: string;
  name: string;
  whatsapp: string;
  email: string;
  document?: string; // CPF or CNPJ
  address?: string;
  password?: string; // Client Portal Access
  createdAt?: string; // New: Date when client was created
}

export interface OrderMessage {
  id: string;
  order_id: string;
  sender: 'client' | 'store';
  message: string;
  created_at: string;
}

export enum UserRole {
  SALES = 'Vendedor',
  SALES_MANAGER = 'Gerente de Venda',
  DESIGNER_CREATIVE = 'Designer Criativo',
  DESIGNER_FINAL = 'Designer Finalização',
  PRODUCTION_OPERATOR = 'Operador Produção',
  PRODUCTION_MANAGER = 'Gerente de Produção'
}

export interface TeamMember {
  id: string;
  name: string;
  role: UserRole;
  active: boolean;
  email?: string;
  visible_password?: string;
  createdAt?: string;
}

export interface CatalogOrderItem {
  productId: string;
  productName: string;
  size: string; // e.g., "P", "M", "G"
  quantity: number;
  notes?: string;
  imageUrl?: string;
}

export interface CatalogOrder {
  id: string;
  clientId: string; // Link to Client
  clientName: string;
  clientTeam?: string; // UI Only
  clientPhone: string;
  createdAt: string;
  status: 'pending' | 'approved' | 'rejected';
  items: CatalogOrderItem[];
  totalEstimated: number;
  notes?: string;
}

export interface InventoryItem {
  id: string;
  name: string;
  category: 'Fabric' | 'Ink' | 'Screen' | 'Other';
  quantity: number;
  unit: string;
  minLevel: number;
}

export interface ProductRecipe {
  id: string;
  productId: string;
  inventoryItemId: string;
  inventoryItemName?: string; // For UI display
  quantityRequired: number;
  unit?: string; // For UI display
}


export interface Transaction {
  id: string;
  type: 'income' | 'expense';
  category: 'sale' | 'material' | 'rent' | 'utility' | 'salary' | 'other';
  amount: number;
  description: string;
  date: string;
  orderId?: string; // Optional link to an Order
  createdAt: string;
}
