import React, { useState, useEffect } from 'react';
import { catalogOrderService } from '../services/catalogOrderService';
import { orderService } from '../services/orderService';
import { CatalogOrder, OrderStatus, OrderType, PaymentStatus } from '../types';
import { CheckCircle2, XCircle, Clock, ShoppingBag } from 'lucide-react';

const CatalogRequests: React.FC = () => {
    const [requests, setRequests] = useState<CatalogOrder[]>([]);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        loadRequests();
    }, []);

    const loadRequests = async () => {
        setLoading(true);
        try {
            const data = await catalogOrderService.getAll();
            // Filter only pending for this view, or show all with status filter?
            // For now show all but emphasize pending
            setRequests((data || []) as CatalogOrder[]);
        } catch (error) {
            console.error("Failed to load requests", error);
        } finally {
            setLoading(false);
        }
    };

    const handleApprove = async (request: CatalogOrder) => {
        if (!confirm(`Aprovar pedido de ${request.clientName} e gerar Pedido de Venda?`)) return;

        try {
            // Extract Team from "Client Name (Team)" format
            const nameMatch = request.clientName.match(/^(.*?)\s*\((.*?)\)$/);
            const finalClientName = nameMatch ? nameMatch[1].trim() : request.clientName;
            const clientTeam = nameMatch ? nameMatch[2].trim() : (request.clientTeam || '');

            // 1. Create Production Order
            await orderService.create({
                clientId: request.clientId,
                clientName: finalClientName,
                clientTeam: clientTeam, // Pass extracted team
                createdAt: new Date().toISOString(),
                deliveryDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(), // Default 7 days
                orderNumber: `CAT-${request.id.substring(0, 6).toUpperCase()}`,
                status: OrderStatus.RECEIVED,
                paymentStatus: PaymentStatus.PENDING,
                orderType: OrderType.SALE,
                totalValue: 0, // Admin needs to price it
                notes: `Pedido vindo do Catálogo. Cliente: ${request.clientName} (${request.clientPhone}).`,
                internalNotes: 'Gerado automaticamente pelo módulo de Catálogo',
                items: request.items.map(item => ({
                    id: '', // Generated by DB
                    productId: item.productId,
                    productName: item.productName,
                    gradeLabel: 'Masculino', // Defaulting, or need to map if size is specific to grade? CatalogOrderItem has size. OrderItem needs gradeLabel?
                    // Wait, OrderItem requires gradeLabel. CatalogOrderItem has size but not Grade.
                    // We might need to infer Grade or set a default "Geral".
                    // Re-checking OrderItem type.
                    size: item.size,
                    quantity: item.quantity,
                    unitPrice: 0,
                    fabricName: 'Padrão', // Default
                    fabricId: 'f1' // Defaulting to first fabric or logic
                })) as any
            });

            // 2. Update Status
            await catalogOrderService.updateStatus(request.id, 'approved');

            alert("Pedido gerado com sucesso! Verifique na tela de Pedidos.");
            loadRequests();

        } catch (error) {
            console.error("Error approving request", error);
            alert("Erro ao aprovar pedido.");
        }
    };

    const handleReject = async (id: string) => {
        if (!confirm("Rejeitar este pedido?")) return;
        try {
            await catalogOrderService.updateStatus(id, 'rejected');
            loadRequests();
        } catch (error) {
            console.error("Error rejecting", error);
        }
    };

    return (
        <div className="space-y-8 animate-in fade-in duration-500">
            <header>
                <h2 className="text-3xl font-black text-slate-100 uppercase tracking-tight">Solicitações do Catálogo</h2>
                <p className="text-slate-500 font-bold">Gerencie os pedidos enviados pelo catálogo online.</p>
            </header>

            <div className="grid gap-4">
                {loading ? (
                    <p className="text-slate-500">Carregando...</p>
                ) : requests.length === 0 ? (
                    <div className="p-10 bg-[#0f172a] rounded-3xl border border-slate-800 text-center">
                        <ShoppingBag className="w-12 h-12 mx-auto text-slate-700 mb-4" />
                        <p className="text-slate-500 font-bold">Nenhuma solicitação encontrada.</p>
                    </div>
                ) : (
                    requests.map(request => (
                        <div key={request.id} className="bg-[#0f172a] p-6 rounded-3xl border border-slate-800 flex flex-col md:flex-row gap-6 relative overflow-hidden group">
                            {/* Status Stripe */}
                            <div className={`absolute left-0 top-0 bottom-0 w-1.5 ${request.status === 'approved' ? 'bg-emerald-500' :
                                request.status === 'rejected' ? 'bg-rose-500' : 'bg-amber-500'
                                }`} />

                            <div className="flex-1 space-y-4">
                                <div className="flex justify-between items-start">
                                    <div>
                                        <h3 className="font-black text-lg text-slate-200 uppercase">{request.clientName}</h3>
                                        <p className="text-xs text-indigo-400 font-bold flex items-center gap-2">
                                            {request.clientPhone}
                                            <span className="w-1 h-1 bg-slate-600 rounded-full" />
                                            {new Date(request.createdAt).toLocaleDateString('pt-BR')}
                                        </p>
                                    </div>
                                    <span className={`px-3 py-1 rounded-full text-[10px] font-black uppercase tracking-widest border ${request.status === 'approved' ? 'bg-emerald-900/30 text-emerald-400 border-emerald-500/30' :
                                        request.status === 'rejected' ? 'bg-rose-900/30 text-rose-400 border-rose-500/30' :
                                            'bg-amber-900/30 text-amber-400 border-amber-500/30'
                                        }`}>
                                        {request.status === 'pending' ? 'Pendente' : request.status === 'approved' ? 'Aprovado' : 'Rejeitado'}
                                    </span>
                                </div>

                                <div className="bg-slate-900/50 p-4 rounded-2xl border border-slate-800 space-y-2">
                                    {request.items.map((item, idx) => (
                                        <div key={idx} className="flex items-center gap-4 text-sm text-slate-300">
                                            <span className="font-bold bg-slate-800 px-2 py-0.5 rounded text-xs text-slate-400">{item.quantity}x</span>
                                            <span className="flex-1">{item.productName} (Tam: {item.size})</span>
                                            {item.notes && <span className="text-[10px] italic text-slate-500">"{item.notes}"</span>}
                                        </div>
                                    ))}
                                </div>
                            </div>

                            {request.status === 'pending' && (
                                <div className="flex flex-col justify-center gap-3 w-full md:w-auto border-t md:border-t-0 md:border-l border-slate-800 pt-4 md:pt-0 md:pl-6">
                                    <button
                                        onClick={() => handleApprove(request)}
                                        className="bg-emerald-600 hover:bg-emerald-500 text-white px-6 py-3 rounded-2xl font-black uppercase text-[10px] tracking-widest flex items-center justify-center gap-2 shadow-lg shadow-emerald-900/20 transition-all"
                                    >
                                        <CheckCircle2 className="w-4 h-4" /> Aprovar
                                    </button>
                                    <button
                                        onClick={() => handleReject(request.id)}
                                        className="bg-slate-800 hover:bg-rose-900/50 hover:text-rose-400 text-slate-400 px-6 py-3 rounded-2xl font-black uppercase text-[10px] tracking-widest flex items-center justify-center gap-2 transition-all"
                                    >
                                        <XCircle className="w-4 h-4" /> Rejeitar
                                    </button>
                                </div>
                            )}
                        </div>
                    ))
                )}
            </div>
        </div>
    );
};

export default CatalogRequests;
